---
title: "dataBLSA_knownProps450K"
output: html_document
---

```{r}
library(ggplot2)
library(cowplot)
library(tidyr)
library(dplyr)
library(minfi)
library(quadprog)
library(here)
# library(methylCC) # on Github


# dataPathCellTypeSpecificDMRs <- "/users/shicks1/projects/methylCC/scripts/data"
# celltypeSpecificDMRegions <- readRDS(file = file.path(dataPathCellTypeSpecificDMRs, "celltypeSpecificDMRegions.RDS"))
# celltypeSpecificDMRegionsSub <- readRDS(file = file.path(dataPathCellTypeSpecificDMRs, "celltypeSpecificDMRegionsSub.RDS"))

dataPath_blsa <- "/users/shicks1/data/DNAm/2017-blsa-450-cellsort"
dataPath_flowSort <- "/users/shicks1/data/DNAm/FlowSortedBlood450k"

# # Create a MethylSet object ('Mset')
# FlowSorted.Blood.450k <- updateObject(FlowSorted.Blood.450k) 
# Mset_train450k <- preprocessIllumina(updateObject(FlowSorted.Blood.450k))
# Mset_train450k <- mapToGenome(Mset_train450k, mergeManifest = FALSE)
# save(Mset_train450k, file=file.path(dataPath_flowSort, "FlowSorted-Mset-Illumina.rda"))
# load(file.path(dataPath_flowSort, "FlowSorted-Mset-Illumina.rda"))

# FlowSorted.Blood.450k <- updateObject(FlowSorted.Blood.450k)
# Mset_train450k <- preprocessQuantile(FlowSorted.Blood.450k)
# Mset_train450k <- mapToGenome(Mset_train450k, mergeManifest = FALSE)
# save(Mset_train450k, file=file.path(dataPath_flowSort, "FlowSorted-Mset-Quantile.rda"))
load(file.path(dataPath_flowSort, "FlowSorted-Mset-Quantile.rda"))


################################################
### Target Data: 806 450K DNA methylation samples with known cell type proportions
################################################

# Flow Sorted measured cell type proportions (806 samples)
trueProps <- read.csv(file.path(dataPath_blsa, 
                                "2017-blsa-celltype-counts.csv"), 
                      header = TRUE)
colnames(trueProps) <- c("sampleID", "baso", "eos", "neu", "lymph", "mono")

# Create a "Gran" column (Baso + Eos + Neu)
trueProps$gran <- trueProps$baso + trueProps$eos + trueProps$neu
trueProps[,-1] <- trueProps[,-1] / 100

# Load 800 samples run on 450K DNA methylation array 
#       with corresponding cell type proportions
load(file.path(dataPath_blsa, "2017-blsa-rgset.rda")) 
RGset <- updateObject(RGset) 

# need to fix "non-forming" names
pData(RGset)$Sex <- ifelse(pData(RGset)$Sex == 1, "M", "F")
pData(RGset)$Slide <- as.numeric(pData(RGset)$Slide)

# Need to filter: 806 samples in trueProps, but only 800 samples in RGset
trueProps <- trueProps[match(pData(RGset)$Sample.ID, trueProps$sampleID), ]
colnames(trueProps) <- c("samples", "Baso", "Eos", "Neu", "Lymph", "Mono", "Gran")

# run minfi::estimateCellCounts() in dataBLSA.R and dataBLSA.sh scripts. 
# counts450K <- estimateCellCounts(RGset)
# save(counts450K, file = file.path(dataPath_blsa, "cellcounts/dataBLSA-minfi-estimateCellCounts.RData"))
load(file.path(dataPath_blsa, "ests/cellcounts/dataBLSA-minfi-estimateCellCounts.RData"))
counts450K <- as.data.frame(counts450K)
counts450K <- counts450K / rowSums(counts450K)
# boxplot(counts450K, y = c(0,1))
counts450K$Lymph <- 
  rowSums(counts450K[, colnames(counts450K) %in% c("CD4T", "CD8T", "NK", "Bcell")])
counts450K <- counts450K[, colnames(counts450K) %in% c("Gran", "Mono", "Lymph")]

##### 
keepSamples <- 1:50 # seq_len(nrow(counts450K)) # 1:50
counts450K <- counts450K[keepSamples,]
boxplot(counts450K, ylim = c(0,1))
df.Houseman <- gather(cbind("samples" = rownames(counts450K), counts450K), celltype, est, -samples)

M1.rmse = mean(sqrt(colMeans((trueProps[keepSamples,5:7] - counts450K[,c(3,1,2)])^2)))
M1.rmse


##### 
regions <- findDMRs(Mset_train450k=Mset_train450k,
                    verbose=TRUE, gr_target=NULL, numRegions=50, numProbes=50,
                    includeCpGs = FALSE, betaCutoff = 0.2, pairwiseComparison=FALSE)
table(mcols(regions$regions)$cellType, mcols(regions$regions)$status)
table(mcols(regions$regions)$cellType,mcols(regions$regions)$L)
plot(regions$regions$dm, -log(regions$regions$p.value))

mypar()
for(i in 500:515){
  regions$regions[i,]
  plot(regions$y[i,],col=rafalib::as.fumeric(as.character(regions$cell)),main=i,ylim=c(0,1))
  abline(h=0.5); 
  legend("bottomright",regions$cellLevels,col=1:6,pch=16)
  Sys.sleep(1)
}


par(mfrow=c(1,2))
image(t(regions$housemanCpGs),  xaxt="n", main = "Houseman top 600 CpGs")
axis(side=1, at=seq(0, 1, by =.2), labels=colnames(regions$zmat))
image(t(regions$profiles),  xaxt="n", main = "DMRs")
axis(side=1, at=seq(0, 1, by =.2), labels=colnames(regions$zmat))

# run compote::estimateCC method in dataBLSA.R and dataBLSA.sh scripts. 
est <- estimateCC(object = RGset[,keepSamples], findRegions = FALSE, 
                  verbose = TRUE, epsilon = 0.01, 
                  maxIter = 100, initParamMethod = "random")
# save(est, file = file.path(dataPath_blsa, "cellcounts/dataBLSA-hicks-estimateCC.RData"))
# load(file.path(dataPath_blsa, "cellcounts/dataBLSA-hicks-estimateCC-208regions.RData"))
counts.450k.Hicks <- cellcounts(est)
rownames(counts.450k.Hicks) <- colnames(RGset[,keepSamples])
# boxplot(counts.450k.Hicks, ylim = c(0,1))
counts.450k.Hicks$Lymph <- 
rowSums(counts.450k.Hicks[, colnames(counts.450k.Hicks) %in% c("CD4T", "CD8T", "NK", "Bcell")])
counts.450k.Hicks <- counts.450k.Hicks[, which(colnames(counts.450k.Hicks) %in% c("Gran", "Mono", "Lymph"))]
par(mfrow=c(1,1)); boxplot(counts.450k.Hicks, ylim = c(0,1))

df.Hicks <- gather(cbind("samples" = rownames(counts.450k.Hicks), counts.450k.Hicks), celltype, est, -samples)

M2.rmse = mean(sqrt(colMeans((trueProps[keepSamples,c("Mono", "Gran", "Lymph")] - 
                                counts.450k.Hicks[,c("Mono", "Gran", "Lymph")])^2)))
M2.rmse


df.trueProps <- gather(cbind("samples" = rownames(counts.450k.Hicks), 
                             trueProps[keepSamples,c(5:7)]), celltype, est, -samples)
dfcombined <- full_join(df.trueProps, df.Houseman,  by = c("samples", "celltype"))
dfcombined <- full_join(dfcombined, df.Hicks,  by = c("samples", "celltype"))
colnames(dfcombined) <- c("samples", "celltype", "Truth", "Houseman", "Hicks")
dfcombined$celltype <- factor(dfcombined$celltype, levels = c("Lymph", "Mono", "Gran"))
dfcombined <- gather(dfcombined, model, est, -c(samples, celltype, Truth))
dfcombined$model <- factor(dfcombined$model, levels = c("Houseman", "Hicks"))

# gmat <- 
dfcombined %>% 
  ggplot(aes(x=Truth, y = est)) + 
    geom_abline(intercept = 0, slope = 1) + xlim(0,1) + ylim(0,1) +
    facet_grid(model ~celltype) + geom_point() +
    xlab("True Cell Composition (measured with flow cytometry)") + ylab("Model-based Cell Composition Estimates")

pdf(file.path(dataPath_blsa, "figs/array_HousemanHicks_scatterplot-403Regions.pdf"), width = 8, height = 5)
print(gmat)
dev.off()


dfcombined %>% 
  ggplot(aes(x=Truth, y = est, colour=celltype)) + 
    geom_abline(intercept = 0, slope = 1) + xlim(0,1) + ylim(0,1) +
    facet_grid(model ~.) + geom_point() +
    xlab("True Cell Composition (measured with flow cytometry)") + ylab("Model-based Cell Composition Estimates")

```


Delete after this point

```{r}
dfcombined <- full_join(df.Houseman, df.Hicks,  by = c("samples", "celltype"))
dfcombined$celltype <- factor(dfcombined$celltype, levels = c("CD8T", "CD4T", "NK", "Bcell", "Mono", "Gran"))

gmat <- dfcombined %>% 
  ggplot(aes(x=est.x, y = est.y)) + 
    geom_abline(intercept = 0, slope = 1) + xlim(0,1) + ylim(0,1) +
    facet_grid( ~celltype) + geom_point() +
    xlab("Reference-based model (Houseman)") + ylab("Proposed model (Hicks)") + 
    labs(title = "Model-based cell composition estimates from whole blood samples (n=800, BLSA data)")

pdf(file.path(dataPath_blsa, "figs/array_HousemanHicks_scatterplot_BLSA_noTruth.pdf"), width = 12, height = 4)
print(gmat)
dev.off()



M2.rmse = mean(sqrt(colMeans((trueProps[,5:7] - cbind("Lymph" = rowSums(cellcounts(est)[,1:2]), 
                                                      cellcounts(est)[,3:4]))^2)))
M2.rmse


df.truth = gather(cbind("samples" = pData(RGset)$Sample.ID, trueProps[, 5:7]), 
             celltype, est, -samples)

df1 = gather(cbind("samples" = pData(RGset)$Sample.ID,
                   cellcounts(est)[,3:4], 
                   "Lymph" = rowSums(cellcounts(est)[,1:2])),
             celltype, est, -samples)

dfcombined <- full_join(df.truth, df1,  by = c("samples", "celltype"))

df2 = gather(cbind("samples" = pData(RGset)$Sample.ID, dat[, c(7,5,6)]), 
             celltype, est, -samples)

dfcombined <- full_join(dfcombined, df2,  by = c("samples", "celltype"))
colnames(dfcombined) <- c("samples", "celltype", "Truth", "Hicks", "Houseman")
dfcombined$celltype <- factor(dfcombined$celltype, levels = c("Lymph", "Mono", "Gran"))

gmat <- dfcombined %>% 
  ggplot(aes(x=Houseman, y = Hicks)) + 
    geom_abline(intercept = 0, slope = 1) + xlim(0,1) + ylim(0,1) +
    facet_grid( ~celltype) + geom_point() +
    xlab("Reference-based model (Houseman)") + ylab("Proposed model (Hicks)") + 
    labs(title = "Model-based cell composition estimates from whole blood samples (n=800, BLSA data)")

pdf(file.path(dataPath_blsa, "figs/array_HousemanHicks_scatterplot_BLSA_noTruth.pdf"), width = 12, height = 4)
print(gmat)
dev.off()


dfcombined <- gather(dfcombined, model, est, -c(samples, celltype, Truth))
dfcombined$model <- factor(dfcombined$model, levels = c("Houseman", "Hicks"))

gmat <- dfcombined %>% 
  ggplot(aes(x=Truth, y = est)) + 
    geom_abline(intercept = 0, slope = 1) + xlim(0,1) + ylim(0,1) +
    facet_grid(model ~celltype) + geom_point() +
    xlab("True Cell Composition (measured with flow cytometry)") + ylab("Model-based Cell Composition Estimates")

pdf(file.path(dataPath_blsa, "figs/array_HousemanHicks_scatterplot.pdf"), width = 8, height = 5)
print(gmat)
dev.off()


```


