---
title: "2019-05-FindBetterDMRs"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(FlowSorted.Blood.450k)
library(rafalib)
library(limma)
library(bumphunter)

library(gplots)
library(RColorBrewer)
library(ggplot2)
library(cowplot)

# creates a own color palette from red to green
my_palette <- colorRampPalette(c("red", "yellow", "green"))(n = 149)

# (optional) defines the color breaks manually for a "skewed" color transition
col_breaks = c(seq(0,.10,length=50),  # for red
  seq(0.11,0.90,length=50),           # for yellow
  seq(0.91,1,length=50))             # for green

dataPath_flowSort <- "/users/shicks1/data/DNAm/FlowSortedBlood450k"
# savePath <- "/users/shicks1/projects/methylCC/scripts/data"
# figPath <- "/users/shicks1/projects/methylCC/figures/celltypespecificDMRegions"

# # Create a MethylSet object ('Mset')
# FlowSorted.Blood.450k <- updateObject(FlowSorted.Blood.450k) 
# Mset_train450k <- preprocessIllumina(updateObject(FlowSorted.Blood.450k))
# Mset_train450k <- mapToGenome(Mset_train450k, mergeManifest = FALSE)
# save(Mset_train450k, file=file.path(dataPath_flowSort, "FlowSorted-Mset-Illumina.rda"))
load(file.path(dataPath_flowSort, "FlowSorted-Mset-Illumina.rda"))

# FlowSorted.Blood.450k <- updateObject(FlowSorted.Blood.450k)
# Mset_train450k <- preprocessQuantile(FlowSorted.Blood.450k)
# Mset_train450k <- mapToGenome(Mset_train450k, mergeManifest = FALSE)
# save(Mset_train450k, file=file.path(workingDir_flowSort, "FlowSorted-Mset-Quantile.rda"))
# load(file.path(dataPath_flowSort, "FlowSorted-Mset-Quantile.rda"))

Mset_train450k
```


## pairwiseComparison = FALSE

### includeDMRs = TRUE, includeCpGs = FALSE

```{r}
output <- find_dmrs(mset_train_flow_sort=Mset_train450k, 
                    verbose = TRUE, gr_target=NULL, 
                    num_regions = 50, num_cpgs = 50,
                    include_cpgs = FALSE, include_dmrs = TRUE, 
                    bumphunter_beta_cutoff = 0.2, # defined by bumphunter
                    dmr_up_cutoff = 0.5, # smaller is better
                    dmr_down_cutoff = 0.4, # smaller is better
                    dmr_pval_cutoff = 1e-11, # default of 1e-11
                    cpg_pval_cutoff = 1e-08, # default of 1e-08
                    cpg_up_dm_cutoff = 0, # ranges from -infinity to 0
                    cpg_down_dm_cutoff = 0, # ranges from 0 to infinity
                    pairwise_comparison = FALSE)
table(duplicated(output$regions_all)) # 
table(output$regions_all$cellType, output$regions_all$L)
table(output$regions_all$cellType, output$regions_all$status)
table(output$regions_all$cellType, output$regions_all$L, 
      output$regions_all$dmr_status, output$regions_all$status)

p1 <- as.data.frame(mcols(output$regions_all)) %>% 
  ggplot(aes(x = dm, y = -log(p.value),
             color = dmr_status)) +
  geom_point() + 
  geom_hline(yintercept=-log(1e-11)) + 
  geom_hline(yintercept=-log(1e-08))


p2 <- as.data.frame(mcols(output$regions_all)) %>% 
  ggplot(aes(x = dm, y = -log(p.value),
             color = cellType)) +
  geom_point() + 
  geom_hline(yintercept=-log(1e-11)) + 
  geom_hline(yintercept=-log(1e-08))

plot_grid(p1, p2)

mypar()
for(i in 51:60){
  output$regions_all[i,]
  plot(output$y_regions[i,], 
       col = rafalib::as.fumeric(as.character(output$cell)), 
       main = i,
       ylim = c(0,1))
  abline(h=0.5); 
  legend("bottomright", output$cell_levels,col=1:6,pch=16)
  Sys.sleep(1)
}

par(mfrow=c(1,3))
image(t(output$cpgs_houseman),  xaxt="n", main = "Houseman top 600 CpGs")
axis(side=1, at=seq(0, 1, by =.2), labels=colnames(output$zmat))
image(t(output$profiles),  xaxt="n", main = "DMRs")
axis(side=1, at=seq(0, 1, by =.2), labels=colnames(output$zmat))
image(t(output$zmat),  xaxt="n", main = "zmat")
axis(side=1, at=seq(0, 1, by =.2), labels=colnames(output$zmat))

p <- getBeta(Mset_train450k[, pData(Mset_train450k)$Sample_Name != "CD8+_105"] ) # beta values
target <- t(apply(as.data.frame(mcols(output$regions_all))[,1:2],1,function(ind){
    colMeans(p[(ind[1]):(ind[2]),,drop=FALSE]) }))
 
##quick and dirty regresion to cell counts:
estimates <- solve(crossprod(output$profiles)) %*% 
                   crossprod(output$profiles,target)
par(mfrow=c(1,1))
image(estimates)

heatmap.2(t(estimates),
  main = "Cell Counts", # heat map title
  notecol="black",      # change font color of cell labels to black
  density.info="none",  # turns off density plot inside color legend
  trace="none",         # turns off trace lines inside the heat map
  col=my_palette,       # use on color palette defined earlier
  breaks=col_breaks,    # enable color transition at specified limits
  dendrogram="row",     # only draw a row dendrogram
  Colv="NA")            # turn off column clustering
```


## pairwiseComparison = TRUE

```{r}
outputPairs <- find_dmrs(mset_train_flow_sort=Mset_train450k, 
                    verbose = TRUE, gr_target=NULL, 
                    num_regions = 50, num_cpgs = 50,
                    include_cpgs = FALSE, include_dmrs = TRUE, 
                    bumphunter_beta_cutoff = 0.2, # defined by bumphunter
                    dmr_up_cutoff = 0.5, # smaller is better
                    dmr_down_cutoff = 0.4, # smaller is better
                    dmr_pval_cutoff = 1e-11, # default of 1e-11
                    cpg_pval_cutoff = 1e-08, # default of 1e-08
                    cpg_up_dm_cutoff = 0, # ranges from -infinity to 0
                    cpg_down_dm_cutoff = 0, # ranges from 0 to infinity
                    pairwise_comparison = TRUE)
table(duplicated(outputPairs$regions_all)) # 
table(outputPairs$regions_all$cellType, outputPairs$regions_all$L)
table(outputPairs$regions_all$cellType, outputPairs$regions_all$status)
table(outputPairs$regions_all$cellType, outputPairs$regions_all$L, 
      outputPairs$regions_all$dmr_status, outputPairs$regions_all$status)

p1 <- as.data.frame(mcols(outputPairs$regions_all)) %>% 
  ggplot(aes(x = dm, y = -log(p.value),
             color = dmr_status)) +
  geom_point() + 
  geom_hline(yintercept=-log(1e-11)) + 
  geom_hline(yintercept=-log(1e-08))


p2 <- as.data.frame(mcols(outputPairs$regions_all)) %>% 
  ggplot(aes(x = dm, y = -log(p.value),
             color = cellType)) +
  geom_point() + 
  geom_hline(yintercept=-log(1e-11)) + 
  geom_hline(yintercept=-log(1e-08))

plot_grid(p1, p2)

mypar()
for(i in 51:60){
  outputPairs$regions_all[i,]
  plot(outputPairs$y_regions[i,], 
       col = rafalib::as.fumeric(as.character(outputPairs$cell)), 
       main = i,
       ylim = c(0,1))
  abline(h=0.5); 
  legend("bottomright", outputPairs$cell_levels,col=1:6,pch=16)
  Sys.sleep(1)
}

par(mfrow=c(1,3))
image(t(outputPairs$cpgs_houseman),  xaxt="n", main = "Houseman top 600 CpGs")
axis(side=1, at=seq(0, 1, by =.2), labels=colnames(outputPairs$zmat))
image(t(outputPairs$profiles),  xaxt="n", main = "DMRs")
axis(side=1, at=seq(0, 1, by =.2), labels=colnames(outputPairs$zmat))
image(t(outputPairs$zmat),  xaxt="n", main = "zmat")
axis(side=1, at=seq(0, 1, by =.2), labels=colnames(outputPairs$zmat))

p <- getBeta(Mset_train450k[, pData(Mset_train450k)$Sample_Name != "CD8+_105"] ) # beta values
target <- t(apply(as.data.frame(mcols(outputPairs$regions_all))[,1:2],1,function(ind){
    colMeans(p[(ind[1]):(ind[2]),,drop=FALSE]) }))
 
##quick and dirty regresion to cell counts:
estimatesPairs <- solve(crossprod(outputPairs$profiles)) %*% 
                   crossprod(outputPairs$profiles,target)
par(mfrow=c(1,1))
image(estimatesPairs)

heatmap.2(t(estimatesPairs),
  main = "Cell Counts", # heat map title
  notecol="black",      # change font color of cell labels to black
  density.info="none",  # turns off density plot inside color legend
  trace="none",         # turns off trace lines inside the heat map
  col=my_palette,       # use on color palette defined earlier
  breaks=col_breaks,    # enable color transition at specified limits
  dendrogram="row",     # only draw a row dendrogram
  Colv="NA")            # turn off column clustering
```


## comparison 

```{r}
dat <- dplyr::full_join(
  cbind(tidyr::gather(as.data.frame(estimates)), 
        celltype = rep(rownames(estimates), ncol(estimates))), 
  cbind(tidyr::gather(as.data.frame(estimatesPairs)), 
         celltype = rep(rownames(estimates), ncol(estimates))), 
  by = c("key", "celltype")) %>% 
  tidyr::separate(key, c("type", "ID"), sep="_")

dat %>% # filter(celltype %in% c( "CD8T")) %>% 
  ggplot(aes(value.x, value.y, color = type)) + 
  geom_point()

```

